# PROD overrides - GKE cluster
namespace: linktracker-prod
baseUrl: "https://136-113-16-41.nip.io"
imagePullPolicy: Always

backend:
  image: shivkumarkonnuri/linktracker:backend-fc4db3c
  replicas: 2
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60

worker:
  image: shivkumarkonnuri/linktracker:worker-fc4db3c

frontend:
  image: shivkumarkonnuri/linktracker:frontend-fc4db3c

configmap:
  dbUrl: "postgresql://linktracker:linktracker@postgres:5432/linktracker"
  redisUrl: "redis://redis:6379/0"

ingress:
  enabled: false   # disable nginx Ingress in prod

gateway:
  enabled: true
  className: gke-l7-regional-external-managed
  staticIpName: linktracker-gateway-ip
  hostname: "136-113-16-41.nip.io"   # e.g. 35-209-77-35.nip.io — nip.io also supports dash format
  tls:
    enabled: true
    secretName: linktracker-tls
    issuerName: letsencrypt-prod

networkPolicy:
  enabled: true
