apiVersion: v1
kind: Secret
metadata:
  name: linktracker-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb }}
