apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resource-finalizer.argocd.argoproj.io
spec:
  project: observability

  source:
    repoURL: https://github.com/shivkumarkonnuri/linktracker-infra
    targetRevision: main
    path: observability/kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
